#############################################################################
# Makefile for building: cms_system
# Generated by qmake (3.0) (Qt 5.5.0)
# Project:  cms_system.pro
# Template: subdirs
# Command: E:\QT\5.5\mingw492_32\bin\qmake.exe "CONFIG+=debug" -o Makefile cms_system.pro
#############################################################################

MAKEFILE      = Makefile

first: make_first
QMAKE         = E:\QT\5.5\mingw492_32\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = copy /y
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = copy /y
INSTALL_PROGRAM = copy /y
INSTALL_DIR   = xcopy /s /q /y /i
DEL_FILE      = del
SYMLINK       = $(QMAKE) -install ln -f -s
DEL_DIR       = rmdir
MOVE          = move
SUBTARGETS    =  \
		sub-helpers \
		sub-models \
		sub-views \
		sub-controllers


sub-helpers-qmake_all:  FORCE
	@if not exist helpers\ mkdir helpers\ & if not exist helpers\ exit 1
	cd helpers\ && $(QMAKE) F:\QTweb\cms_system\helpers\helpers.pro "CONFIG+=debug" -o Makefile
	cd helpers\ && $(MAKE) -f Makefile qmake_all
sub-helpers: FORCE
	@if not exist helpers\ mkdir helpers\ & if not exist helpers\ exit 1
	cd helpers\ && ( if not exist Makefile $(QMAKE) F:\QTweb\cms_system\helpers\helpers.pro "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile
sub-helpers-make_first-ordered: FORCE
	@if not exist helpers\ mkdir helpers\ & if not exist helpers\ exit 1
	cd helpers\ && ( if not exist Makefile $(QMAKE) F:\QTweb\cms_system\helpers\helpers.pro "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile 
sub-helpers-make_first: FORCE
	@if not exist helpers\ mkdir helpers\ & if not exist helpers\ exit 1
	cd helpers\ && ( if not exist Makefile $(QMAKE) F:\QTweb\cms_system\helpers\helpers.pro "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile 
sub-helpers-all-ordered: FORCE
	@if not exist helpers\ mkdir helpers\ & if not exist helpers\ exit 1
	cd helpers\ && ( if not exist Makefile $(QMAKE) F:\QTweb\cms_system\helpers\helpers.pro "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile all
sub-helpers-all: FORCE
	@if not exist helpers\ mkdir helpers\ & if not exist helpers\ exit 1
	cd helpers\ && ( if not exist Makefile $(QMAKE) F:\QTweb\cms_system\helpers\helpers.pro "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile all
sub-helpers-clean-ordered: FORCE
	@if not exist helpers\ mkdir helpers\ & if not exist helpers\ exit 1
	cd helpers\ && ( if not exist Makefile $(QMAKE) F:\QTweb\cms_system\helpers\helpers.pro "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile clean
sub-helpers-clean: FORCE
	@if not exist helpers\ mkdir helpers\ & if not exist helpers\ exit 1
	cd helpers\ && ( if not exist Makefile $(QMAKE) F:\QTweb\cms_system\helpers\helpers.pro "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile clean
sub-helpers-distclean-ordered: FORCE
	@if not exist helpers\ mkdir helpers\ & if not exist helpers\ exit 1
	cd helpers\ && ( if not exist Makefile $(QMAKE) F:\QTweb\cms_system\helpers\helpers.pro "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile distclean
sub-helpers-distclean: FORCE
	@if not exist helpers\ mkdir helpers\ & if not exist helpers\ exit 1
	cd helpers\ && ( if not exist Makefile $(QMAKE) F:\QTweb\cms_system\helpers\helpers.pro "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile distclean
sub-helpers-install_subtargets-ordered: FORCE
	@if not exist helpers\ mkdir helpers\ & if not exist helpers\ exit 1
	cd helpers\ && ( if not exist Makefile $(QMAKE) F:\QTweb\cms_system\helpers\helpers.pro "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile install
sub-helpers-install_subtargets: FORCE
	@if not exist helpers\ mkdir helpers\ & if not exist helpers\ exit 1
	cd helpers\ && ( if not exist Makefile $(QMAKE) F:\QTweb\cms_system\helpers\helpers.pro "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile install
sub-helpers-uninstall_subtargets-ordered: FORCE
	@if not exist helpers\ mkdir helpers\ & if not exist helpers\ exit 1
	cd helpers\ && ( if not exist Makefile $(QMAKE) F:\QTweb\cms_system\helpers\helpers.pro "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-helpers-uninstall_subtargets: FORCE
	@if not exist helpers\ mkdir helpers\ & if not exist helpers\ exit 1
	cd helpers\ && ( if not exist Makefile $(QMAKE) F:\QTweb\cms_system\helpers\helpers.pro "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-models-qmake_all: sub-helpers-qmake_all FORCE
	@if not exist models\ mkdir models\ & if not exist models\ exit 1
	cd models\ && $(QMAKE) F:\QTweb\cms_system\models\models.pro "CONFIG+=debug" -o Makefile
	cd models\ && $(MAKE) -f Makefile qmake_all
sub-models: FORCE
	@if not exist models\ mkdir models\ & if not exist models\ exit 1
	cd models\ && ( if not exist Makefile $(QMAKE) F:\QTweb\cms_system\models\models.pro "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile
sub-models-make_first-ordered: sub-helpers-make_first-ordered  FORCE
	@if not exist models\ mkdir models\ & if not exist models\ exit 1
	cd models\ && ( if not exist Makefile $(QMAKE) F:\QTweb\cms_system\models\models.pro "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile 
sub-models-make_first: FORCE
	@if not exist models\ mkdir models\ & if not exist models\ exit 1
	cd models\ && ( if not exist Makefile $(QMAKE) F:\QTweb\cms_system\models\models.pro "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile 
sub-models-all-ordered: sub-helpers-all-ordered  FORCE
	@if not exist models\ mkdir models\ & if not exist models\ exit 1
	cd models\ && ( if not exist Makefile $(QMAKE) F:\QTweb\cms_system\models\models.pro "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile all
sub-models-all: FORCE
	@if not exist models\ mkdir models\ & if not exist models\ exit 1
	cd models\ && ( if not exist Makefile $(QMAKE) F:\QTweb\cms_system\models\models.pro "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile all
sub-models-clean-ordered: sub-helpers-clean-ordered  FORCE
	@if not exist models\ mkdir models\ & if not exist models\ exit 1
	cd models\ && ( if not exist Makefile $(QMAKE) F:\QTweb\cms_system\models\models.pro "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile clean
sub-models-clean: FORCE
	@if not exist models\ mkdir models\ & if not exist models\ exit 1
	cd models\ && ( if not exist Makefile $(QMAKE) F:\QTweb\cms_system\models\models.pro "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile clean
sub-models-distclean-ordered: sub-helpers-distclean-ordered  FORCE
	@if not exist models\ mkdir models\ & if not exist models\ exit 1
	cd models\ && ( if not exist Makefile $(QMAKE) F:\QTweb\cms_system\models\models.pro "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile distclean
sub-models-distclean: FORCE
	@if not exist models\ mkdir models\ & if not exist models\ exit 1
	cd models\ && ( if not exist Makefile $(QMAKE) F:\QTweb\cms_system\models\models.pro "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile distclean
sub-models-install_subtargets-ordered: sub-helpers-install_subtargets-ordered  FORCE
	@if not exist models\ mkdir models\ & if not exist models\ exit 1
	cd models\ && ( if not exist Makefile $(QMAKE) F:\QTweb\cms_system\models\models.pro "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile install
sub-models-install_subtargets: FORCE
	@if not exist models\ mkdir models\ & if not exist models\ exit 1
	cd models\ && ( if not exist Makefile $(QMAKE) F:\QTweb\cms_system\models\models.pro "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile install
sub-models-uninstall_subtargets-ordered: sub-helpers-uninstall_subtargets-ordered  FORCE
	@if not exist models\ mkdir models\ & if not exist models\ exit 1
	cd models\ && ( if not exist Makefile $(QMAKE) F:\QTweb\cms_system\models\models.pro "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-models-uninstall_subtargets: FORCE
	@if not exist models\ mkdir models\ & if not exist models\ exit 1
	cd models\ && ( if not exist Makefile $(QMAKE) F:\QTweb\cms_system\models\models.pro "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-views-qmake_all: sub-models-qmake_all FORCE
	@if not exist views\ mkdir views\ & if not exist views\ exit 1
	cd views\ && $(QMAKE) F:\QTweb\cms_system\views\views.pro "CONFIG+=debug" -o Makefile
	cd views\ && $(MAKE) -f Makefile qmake_all
sub-views: FORCE
	@if not exist views\ mkdir views\ & if not exist views\ exit 1
	cd views\ && ( if not exist Makefile $(QMAKE) F:\QTweb\cms_system\views\views.pro "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile
sub-views-make_first-ordered: sub-models-make_first-ordered  FORCE
	@if not exist views\ mkdir views\ & if not exist views\ exit 1
	cd views\ && ( if not exist Makefile $(QMAKE) F:\QTweb\cms_system\views\views.pro "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile 
sub-views-make_first: FORCE
	@if not exist views\ mkdir views\ & if not exist views\ exit 1
	cd views\ && ( if not exist Makefile $(QMAKE) F:\QTweb\cms_system\views\views.pro "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile 
sub-views-all-ordered: sub-models-all-ordered  FORCE
	@if not exist views\ mkdir views\ & if not exist views\ exit 1
	cd views\ && ( if not exist Makefile $(QMAKE) F:\QTweb\cms_system\views\views.pro "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile all
sub-views-all: FORCE
	@if not exist views\ mkdir views\ & if not exist views\ exit 1
	cd views\ && ( if not exist Makefile $(QMAKE) F:\QTweb\cms_system\views\views.pro "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile all
sub-views-clean-ordered: sub-models-clean-ordered  FORCE
	@if not exist views\ mkdir views\ & if not exist views\ exit 1
	cd views\ && ( if not exist Makefile $(QMAKE) F:\QTweb\cms_system\views\views.pro "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile clean
sub-views-clean: FORCE
	@if not exist views\ mkdir views\ & if not exist views\ exit 1
	cd views\ && ( if not exist Makefile $(QMAKE) F:\QTweb\cms_system\views\views.pro "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile clean
sub-views-distclean-ordered: sub-models-distclean-ordered  FORCE
	@if not exist views\ mkdir views\ & if not exist views\ exit 1
	cd views\ && ( if not exist Makefile $(QMAKE) F:\QTweb\cms_system\views\views.pro "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile distclean
sub-views-distclean: FORCE
	@if not exist views\ mkdir views\ & if not exist views\ exit 1
	cd views\ && ( if not exist Makefile $(QMAKE) F:\QTweb\cms_system\views\views.pro "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile distclean
sub-views-install_subtargets-ordered: sub-models-install_subtargets-ordered  FORCE
	@if not exist views\ mkdir views\ & if not exist views\ exit 1
	cd views\ && ( if not exist Makefile $(QMAKE) F:\QTweb\cms_system\views\views.pro "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile install
sub-views-install_subtargets: FORCE
	@if not exist views\ mkdir views\ & if not exist views\ exit 1
	cd views\ && ( if not exist Makefile $(QMAKE) F:\QTweb\cms_system\views\views.pro "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile install
sub-views-uninstall_subtargets-ordered: sub-models-uninstall_subtargets-ordered  FORCE
	@if not exist views\ mkdir views\ & if not exist views\ exit 1
	cd views\ && ( if not exist Makefile $(QMAKE) F:\QTweb\cms_system\views\views.pro "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-views-uninstall_subtargets: FORCE
	@if not exist views\ mkdir views\ & if not exist views\ exit 1
	cd views\ && ( if not exist Makefile $(QMAKE) F:\QTweb\cms_system\views\views.pro "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-controllers-qmake_all: sub-views-qmake_all FORCE
	@if not exist controllers\ mkdir controllers\ & if not exist controllers\ exit 1
	cd controllers\ && $(QMAKE) F:\QTweb\cms_system\controllers\controllers.pro "CONFIG+=debug" -o Makefile
	cd controllers\ && $(MAKE) -f Makefile qmake_all
sub-controllers: FORCE
	@if not exist controllers\ mkdir controllers\ & if not exist controllers\ exit 1
	cd controllers\ && ( if not exist Makefile $(QMAKE) F:\QTweb\cms_system\controllers\controllers.pro "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile
sub-controllers-make_first-ordered: sub-views-make_first-ordered  FORCE
	@if not exist controllers\ mkdir controllers\ & if not exist controllers\ exit 1
	cd controllers\ && ( if not exist Makefile $(QMAKE) F:\QTweb\cms_system\controllers\controllers.pro "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile 
sub-controllers-make_first: FORCE
	@if not exist controllers\ mkdir controllers\ & if not exist controllers\ exit 1
	cd controllers\ && ( if not exist Makefile $(QMAKE) F:\QTweb\cms_system\controllers\controllers.pro "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile 
sub-controllers-all-ordered: sub-views-all-ordered  FORCE
	@if not exist controllers\ mkdir controllers\ & if not exist controllers\ exit 1
	cd controllers\ && ( if not exist Makefile $(QMAKE) F:\QTweb\cms_system\controllers\controllers.pro "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile all
sub-controllers-all: FORCE
	@if not exist controllers\ mkdir controllers\ & if not exist controllers\ exit 1
	cd controllers\ && ( if not exist Makefile $(QMAKE) F:\QTweb\cms_system\controllers\controllers.pro "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile all
sub-controllers-clean-ordered: sub-views-clean-ordered  FORCE
	@if not exist controllers\ mkdir controllers\ & if not exist controllers\ exit 1
	cd controllers\ && ( if not exist Makefile $(QMAKE) F:\QTweb\cms_system\controllers\controllers.pro "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile clean
sub-controllers-clean: FORCE
	@if not exist controllers\ mkdir controllers\ & if not exist controllers\ exit 1
	cd controllers\ && ( if not exist Makefile $(QMAKE) F:\QTweb\cms_system\controllers\controllers.pro "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile clean
sub-controllers-distclean-ordered: sub-views-distclean-ordered  FORCE
	@if not exist controllers\ mkdir controllers\ & if not exist controllers\ exit 1
	cd controllers\ && ( if not exist Makefile $(QMAKE) F:\QTweb\cms_system\controllers\controllers.pro "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile distclean
sub-controllers-distclean: FORCE
	@if not exist controllers\ mkdir controllers\ & if not exist controllers\ exit 1
	cd controllers\ && ( if not exist Makefile $(QMAKE) F:\QTweb\cms_system\controllers\controllers.pro "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile distclean
sub-controllers-install_subtargets-ordered: sub-views-install_subtargets-ordered  FORCE
	@if not exist controllers\ mkdir controllers\ & if not exist controllers\ exit 1
	cd controllers\ && ( if not exist Makefile $(QMAKE) F:\QTweb\cms_system\controllers\controllers.pro "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile install
sub-controllers-install_subtargets: FORCE
	@if not exist controllers\ mkdir controllers\ & if not exist controllers\ exit 1
	cd controllers\ && ( if not exist Makefile $(QMAKE) F:\QTweb\cms_system\controllers\controllers.pro "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile install
sub-controllers-uninstall_subtargets-ordered: sub-views-uninstall_subtargets-ordered  FORCE
	@if not exist controllers\ mkdir controllers\ & if not exist controllers\ exit 1
	cd controllers\ && ( if not exist Makefile $(QMAKE) F:\QTweb\cms_system\controllers\controllers.pro "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-controllers-uninstall_subtargets: FORCE
	@if not exist controllers\ mkdir controllers\ & if not exist controllers\ exit 1
	cd controllers\ && ( if not exist Makefile $(QMAKE) F:\QTweb\cms_system\controllers\controllers.pro "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile uninstall

Makefile: cms_system.pro E:/QT/5.5/mingw492_32/mkspecs/win32-g++/qmake.conf E:/QT/5.5/mingw492_32/mkspecs/features/spec_pre.prf \
		E:/QT/5.5/mingw492_32/mkspecs/qdevice.pri \
		E:/QT/5.5/mingw492_32/mkspecs/features/device_config.prf \
		E:/QT/5.5/mingw492_32/mkspecs/qconfig.pri \
		E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_3dcore.pri \
		E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_3dcore_private.pri \
		E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_3dinput.pri \
		E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_3dinput_private.pri \
		E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_3dquick.pri \
		E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_3dquick_private.pri \
		E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_3dquickrenderer.pri \
		E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_3dquickrenderer_private.pri \
		E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_3drenderer.pri \
		E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_3drenderer_private.pri \
		E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_axbase.pri \
		E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_axbase_private.pri \
		E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_axcontainer.pri \
		E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_axcontainer_private.pri \
		E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_axserver.pri \
		E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_axserver_private.pri \
		E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_bluetooth.pri \
		E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_bluetooth_private.pri \
		E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_bootstrap_private.pri \
		E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_clucene_private.pri \
		E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_concurrent.pri \
		E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_concurrent_private.pri \
		E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_core.pri \
		E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_core_private.pri \
		E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_dbus.pri \
		E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_dbus_private.pri \
		E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_declarative.pri \
		E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_declarative_private.pri \
		E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_designer.pri \
		E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_designer_private.pri \
		E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_designercomponents_private.pri \
		E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_enginio.pri \
		E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_enginio_private.pri \
		E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_gui.pri \
		E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_gui_private.pri \
		E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_help.pri \
		E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_help_private.pri \
		E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_location.pri \
		E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_location_private.pri \
		E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_multimedia.pri \
		E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_multimedia_private.pri \
		E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_multimediawidgets.pri \
		E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_network.pri \
		E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_network_private.pri \
		E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_nfc.pri \
		E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_nfc_private.pri \
		E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_opengl.pri \
		E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_opengl_private.pri \
		E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_openglextensions.pri \
		E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_openglextensions_private.pri \
		E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_platformsupport_private.pri \
		E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_positioning.pri \
		E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_positioning_private.pri \
		E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_printsupport.pri \
		E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_printsupport_private.pri \
		E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_qml.pri \
		E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_qml_private.pri \
		E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_qmltest.pri \
		E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_qmltest_private.pri \
		E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_quick.pri \
		E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_quick_private.pri \
		E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_quickparticles_private.pri \
		E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_quickwidgets.pri \
		E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_script.pri \
		E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_script_private.pri \
		E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_scripttools.pri \
		E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_scripttools_private.pri \
		E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_sensors.pri \
		E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_sensors_private.pri \
		E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_serialport.pri \
		E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_serialport_private.pri \
		E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_sql.pri \
		E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_sql_private.pri \
		E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_svg.pri \
		E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_svg_private.pri \
		E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_testlib.pri \
		E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_testlib_private.pri \
		E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_uiplugin.pri \
		E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_uitools.pri \
		E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_uitools_private.pri \
		E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_webchannel.pri \
		E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_webchannel_private.pri \
		E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_webkit.pri \
		E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_webkit_private.pri \
		E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_webkitwidgets.pri \
		E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_websockets.pri \
		E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_websockets_private.pri \
		E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_widgets.pri \
		E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_widgets_private.pri \
		E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_winextras.pri \
		E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_winextras_private.pri \
		E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_xml.pri \
		E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_xml_private.pri \
		E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_xmlpatterns.pri \
		E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		E:/QT/5.5/mingw492_32/mkspecs/features/qt_functions.prf \
		E:/QT/5.5/mingw492_32/mkspecs/features/qt_config.prf \
		E:/QT/5.5/mingw492_32/mkspecs/features/win32/qt_config.prf \
		E:/QT/5.5/mingw492_32/mkspecs/win32-g++/qmake.conf \
		E:/QT/5.5/mingw492_32/mkspecs/features/spec_post.prf \
		E:/QT/5.5/mingw492_32/mkspecs/features/exclusive_builds.prf \
		E:/QT/5.5/mingw492_32/mkspecs/features/default_pre.prf \
		E:/QT/5.5/mingw492_32/mkspecs/features/win32/default_pre.prf \
		E:/QT/5.5/mingw492_32/mkspecs/features/resolve_config.prf \
		E:/QT/5.5/mingw492_32/mkspecs/features/exclusive_builds_post.prf \
		E:/QT/5.5/mingw492_32/mkspecs/features/default_post.prf \
		E:/QT/5.5/mingw492_32/mkspecs/features/win32/rtti.prf \
		E:/QT/5.5/mingw492_32/mkspecs/features/precompile_header.prf \
		E:/QT/5.5/mingw492_32/mkspecs/features/warn_on.prf \
		E:/QT/5.5/mingw492_32/mkspecs/features/win32/windows.prf \
		E:/QT/5.5/mingw492_32/mkspecs/features/testcase_targets.prf \
		E:/QT/5.5/mingw492_32/mkspecs/features/exceptions.prf \
		E:/QT/5.5/mingw492_32/mkspecs/features/yacc.prf \
		E:/QT/5.5/mingw492_32/mkspecs/features/lex.prf \
		cms_system.pro
	$(QMAKE) "CONFIG+=debug" -o Makefile cms_system.pro
E:/QT/5.5/mingw492_32/mkspecs/features/spec_pre.prf:
E:/QT/5.5/mingw492_32/mkspecs/qdevice.pri:
E:/QT/5.5/mingw492_32/mkspecs/features/device_config.prf:
E:/QT/5.5/mingw492_32/mkspecs/qconfig.pri:
E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_3dcore.pri:
E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_3dcore_private.pri:
E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_3dinput.pri:
E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_3dinput_private.pri:
E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_3dquick.pri:
E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_3dquick_private.pri:
E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_3dquickrenderer.pri:
E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_3dquickrenderer_private.pri:
E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_3drenderer.pri:
E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_3drenderer_private.pri:
E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_axbase.pri:
E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_axbase_private.pri:
E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_axcontainer.pri:
E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_axcontainer_private.pri:
E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_axserver.pri:
E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_axserver_private.pri:
E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_bluetooth.pri:
E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_bluetooth_private.pri:
E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_bootstrap_private.pri:
E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_clucene_private.pri:
E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_concurrent.pri:
E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_concurrent_private.pri:
E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_core.pri:
E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_core_private.pri:
E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_dbus.pri:
E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_dbus_private.pri:
E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_declarative.pri:
E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_declarative_private.pri:
E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_designer.pri:
E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_designer_private.pri:
E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_designercomponents_private.pri:
E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_enginio.pri:
E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_enginio_private.pri:
E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_gui.pri:
E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_gui_private.pri:
E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_help.pri:
E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_help_private.pri:
E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_location.pri:
E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_location_private.pri:
E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_multimedia.pri:
E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_multimedia_private.pri:
E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_multimediawidgets.pri:
E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_network.pri:
E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_network_private.pri:
E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_nfc.pri:
E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_nfc_private.pri:
E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_opengl.pri:
E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_opengl_private.pri:
E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_openglextensions.pri:
E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_openglextensions_private.pri:
E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_platformsupport_private.pri:
E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_positioning.pri:
E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_positioning_private.pri:
E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_printsupport.pri:
E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_printsupport_private.pri:
E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_qml.pri:
E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_qml_private.pri:
E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_qmldevtools_private.pri:
E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_qmltest.pri:
E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_qmltest_private.pri:
E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_quick.pri:
E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_quick_private.pri:
E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_quickparticles_private.pri:
E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_quickwidgets.pri:
E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_quickwidgets_private.pri:
E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_script.pri:
E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_script_private.pri:
E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_scripttools.pri:
E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_scripttools_private.pri:
E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_sensors.pri:
E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_sensors_private.pri:
E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_serialport.pri:
E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_serialport_private.pri:
E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_sql.pri:
E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_sql_private.pri:
E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_svg.pri:
E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_svg_private.pri:
E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_testlib.pri:
E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_testlib_private.pri:
E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_uiplugin.pri:
E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_uitools.pri:
E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_uitools_private.pri:
E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_webchannel.pri:
E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_webchannel_private.pri:
E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_webkit.pri:
E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_webkit_private.pri:
E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_webkitwidgets.pri:
E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_websockets.pri:
E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_websockets_private.pri:
E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_widgets.pri:
E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_widgets_private.pri:
E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_winextras.pri:
E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_winextras_private.pri:
E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_xml.pri:
E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_xml_private.pri:
E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_xmlpatterns.pri:
E:/QT/5.5/mingw492_32/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
E:/QT/5.5/mingw492_32/mkspecs/features/qt_functions.prf:
E:/QT/5.5/mingw492_32/mkspecs/features/qt_config.prf:
E:/QT/5.5/mingw492_32/mkspecs/features/win32/qt_config.prf:
E:/QT/5.5/mingw492_32/mkspecs/win32-g++/qmake.conf:
E:/QT/5.5/mingw492_32/mkspecs/features/spec_post.prf:
E:/QT/5.5/mingw492_32/mkspecs/features/exclusive_builds.prf:
E:/QT/5.5/mingw492_32/mkspecs/features/default_pre.prf:
E:/QT/5.5/mingw492_32/mkspecs/features/win32/default_pre.prf:
E:/QT/5.5/mingw492_32/mkspecs/features/resolve_config.prf:
E:/QT/5.5/mingw492_32/mkspecs/features/exclusive_builds_post.prf:
E:/QT/5.5/mingw492_32/mkspecs/features/default_post.prf:
E:/QT/5.5/mingw492_32/mkspecs/features/win32/rtti.prf:
E:/QT/5.5/mingw492_32/mkspecs/features/precompile_header.prf:
E:/QT/5.5/mingw492_32/mkspecs/features/warn_on.prf:
E:/QT/5.5/mingw492_32/mkspecs/features/win32/windows.prf:
E:/QT/5.5/mingw492_32/mkspecs/features/testcase_targets.prf:
E:/QT/5.5/mingw492_32/mkspecs/features/exceptions.prf:
E:/QT/5.5/mingw492_32/mkspecs/features/yacc.prf:
E:/QT/5.5/mingw492_32/mkspecs/features/lex.prf:
cms_system.pro:
qmake: FORCE
	@$(QMAKE) "CONFIG+=debug" -o Makefile cms_system.pro

qmake_all: sub-helpers-qmake_all sub-models-qmake_all sub-views-qmake_all sub-controllers-qmake_all FORCE

make_first: sub-helpers-make_first-ordered sub-models-make_first-ordered sub-views-make_first-ordered sub-controllers-make_first-ordered  FORCE
all: sub-helpers-all-ordered sub-models-all-ordered sub-views-all-ordered sub-controllers-all-ordered  FORCE
clean: sub-helpers-clean-ordered sub-models-clean-ordered sub-views-clean-ordered sub-controllers-clean-ordered  FORCE
distclean: sub-helpers-distclean-ordered sub-models-distclean-ordered sub-views-distclean-ordered sub-controllers-distclean-ordered  FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-helpers-install_subtargets-ordered sub-models-install_subtargets-ordered sub-views-install_subtargets-ordered sub-controllers-install_subtargets-ordered FORCE
uninstall_subtargets: sub-helpers-uninstall_subtargets-ordered sub-models-uninstall_subtargets-ordered sub-views-uninstall_subtargets-ordered sub-controllers-uninstall_subtargets-ordered FORCE

sub-helpers-debug_ordered:
	@if not exist helpers\ mkdir helpers\ & if not exist helpers\ exit 1
	cd helpers\ && ( if not exist Makefile $(QMAKE) F:\QTweb\cms_system\helpers\helpers.pro "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile debug
sub-models-debug_ordered: sub-helpers-debug_ordered 
	@if not exist models\ mkdir models\ & if not exist models\ exit 1
	cd models\ && ( if not exist Makefile $(QMAKE) F:\QTweb\cms_system\models\models.pro "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile debug
sub-views-debug_ordered: sub-models-debug_ordered 
	@if not exist views\ mkdir views\ & if not exist views\ exit 1
	cd views\ && ( if not exist Makefile $(QMAKE) F:\QTweb\cms_system\views\views.pro "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile debug
sub-controllers-debug_ordered: sub-views-debug_ordered 
	@if not exist controllers\ mkdir controllers\ & if not exist controllers\ exit 1
	cd controllers\ && ( if not exist Makefile $(QMAKE) F:\QTweb\cms_system\controllers\controllers.pro "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile debug
debug: sub-helpers-debug_ordered sub-models-debug_ordered sub-views-debug_ordered sub-controllers-debug_ordered

sub-helpers-release_ordered:
	@if not exist helpers\ mkdir helpers\ & if not exist helpers\ exit 1
	cd helpers\ && ( if not exist Makefile $(QMAKE) F:\QTweb\cms_system\helpers\helpers.pro "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile release
sub-models-release_ordered: sub-helpers-release_ordered 
	@if not exist models\ mkdir models\ & if not exist models\ exit 1
	cd models\ && ( if not exist Makefile $(QMAKE) F:\QTweb\cms_system\models\models.pro "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile release
sub-views-release_ordered: sub-models-release_ordered 
	@if not exist views\ mkdir views\ & if not exist views\ exit 1
	cd views\ && ( if not exist Makefile $(QMAKE) F:\QTweb\cms_system\views\views.pro "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile release
sub-controllers-release_ordered: sub-views-release_ordered 
	@if not exist controllers\ mkdir controllers\ & if not exist controllers\ exit 1
	cd controllers\ && ( if not exist Makefile $(QMAKE) F:\QTweb\cms_system\controllers\controllers.pro "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile release
release: sub-helpers-release_ordered sub-models-release_ordered sub-views-release_ordered sub-controllers-release_ordered

sub-helpers-check_ordered:
	@if not exist helpers\ mkdir helpers\ & if not exist helpers\ exit 1
	cd helpers\ && ( if not exist Makefile $(QMAKE) F:\QTweb\cms_system\helpers\helpers.pro "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile check
sub-models-check_ordered: sub-helpers-check_ordered 
	@if not exist models\ mkdir models\ & if not exist models\ exit 1
	cd models\ && ( if not exist Makefile $(QMAKE) F:\QTweb\cms_system\models\models.pro "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile check
sub-views-check_ordered: sub-models-check_ordered 
	@if not exist views\ mkdir views\ & if not exist views\ exit 1
	cd views\ && ( if not exist Makefile $(QMAKE) F:\QTweb\cms_system\views\views.pro "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile check
sub-controllers-check_ordered: sub-views-check_ordered 
	@if not exist controllers\ mkdir controllers\ & if not exist controllers\ exit 1
	cd controllers\ && ( if not exist Makefile $(QMAKE) F:\QTweb\cms_system\controllers\controllers.pro "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile check
check: sub-helpers-check_ordered sub-models-check_ordered sub-views-check_ordered sub-controllers-check_ordered
install:install_subtargets  FORCE

uninstall: uninstall_subtargets FORCE

FORCE:

